### ISSUE TITLE
请问数据库导入sql在哪里？

### ISSUE THREAD

**Issue by juyufeng** [ego008/goyoubbs#1]
您好！
请问数据库导入sql在哪里？php版的里面是有的youbbs_mysql.sql。

**Comment by ego008** [comment]
你指的是新站初始化还是老站旧数据导入?

**Comment by jingjing0327** [comment]
老站的旧数据如何导入呢？

**Comment by ego008** [comment]
@jingjing0327 参见 https://www.youbbs.org/t/2110
