### ISSUE TITLE
wget site.zip 404

### ISSUE THREAD

**Issue by aruis** [ego008/goyoubbs#12]
`
wget https://github.com/ego008/goyoubbs/releases/download/master/site.zip
--2018-10-30 09:45:20--  https://github.com/ego008/goyoubbs/releases/download/master/site.zip
正在解析主机 github.com (github.com)... 192.30.253.113, 192.30.253.112
正在连接 github.com (github.com)|192.30.253.113|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2018-10-30 09:45:22 错误 404：Not Found。
`

**Comment by ego008** [comment]
Fied
