### ISSUE TITLE
大佬官方也不支持中文账号吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ego008/goyoubbs#14]
![image](https://user-images.githubusercontent.com/12076232/51602747-bc5c9f00-1f42-11e9-85de-5304b9c8881b.png)

我在youbbs论坛注册 上面有写支持中文的啊 怎么却报错呢？

**Comment by ego008** [comment]
程序支持，但需要自己改一下，就是两个函数的区别。

https://github.com/ego008/goyoubbs/blob/master/util/stringcheck.go#L13

`IsNickname` 和 `IsUserName`

```
	nicknameRegexp    = regexp.MustCompile(`^[a-z0-9A-Z\p{Han}]+(_[a-z0-9A-Z\p{Han}]+)*$`)
	usernameRegexp    = regexp.MustCompile(`^[a-zA-Z][a-z0-9A-Z]*(_[a-z0-9A-Z]+)*$`)
```

**Comment by ego008** [comment]
取全部话题的方法可参考 下面的函数

https://github.com/ego008/goyoubbs/blob/61b759543197a4cb3347d666eaa807fc70d68fe2/model/category.go#L64

函数`CategoryNewest` 里有一个变量 `limit`

**Comment by Yakumo-Yukari** [comment]
> > 取全部话题的方法可参考 下面的函数
> > [goyoubbs/model/category.go](https://github.com/ego008/goyoubbs/blob/61b759543197a4cb3347d666eaa807fc70d68fe2/model/category.go#L64)
> > Line 64 in [61b7595](/ego008/goyoubbs/commit/61b759543197a4cb3347d666eaa807fc70d68fe2)
> > func CategoryNewest(db *youdb.DB, limit int) []CategoryMini {
> > 函数`CategoryNewest` 里有一个变量 `limit`
> 
> 谢谢大佬 我研究研究



> 取全部话题的方法可参考 下面的函数
> 
> [goyoubbs/model/category.go](https://github.com/ego008/goyoubbs/blob/61b759543197a4cb3347d666eaa807fc70d68fe2/model/category.go#L64)
> 
> Line 64 in [61b7595](/ego008/goyoubbs/commit/61b759543197a4cb3347d666eaa807fc70d68fe2)
> 
>  func CategoryNewest(db *youdb.DB, limit int) []CategoryMini { 
> 函数`CategoryNewest` 里有一个变量 `limit`

func CategoryNewest(db *youdb.DB, limit int) []CategoryMini {
    var items []CategoryMini
    rs := db.Hrscan("category", []byte(""), limit)
    if rs.State == "ok" {
        for i := 0; i < len(rs.Data)-1; i += 2 {
            item := CategoryMini{}
            json.Unmarshal(rs.Data[i+1], &item)
            items = append(items, item)
        }
    }
    return items
}

根据你的提示在这里折腾了下  这里是不是已经是取出了全部的话题分类？然后倒序排列的话题顺序？

如果这里没用没有取出全部  老大能帮忙改造下吗  想正序取出全部话题分类显示，昨天折腾了下一直没成功。。。。

**Comment by ego008** [comment]
`Hrscan` 是反序
`Hscan` 是正序

limit 改为足够大（大于等于分类总数）

**Comment by Yakumo-Yukari** [comment]
> `Hrscan` 是反序
> `Hscan` 是正序
> 
> limit 改为足够大（大于等于分类总数）

谢谢 老大  我试试看
