### ISSUE TITLE
老大怎么判断帖内输出模板

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ego008/goyoubbs#15]
我现在想只在帖内右侧输出一个div框架，然后参考了下前面你的代码  用{{if ne .PageName "home"}} 判断不等于home的时候输出 但是有个问题是  在话题分类里也会输出  但是我只想在帖内页面输出 看了下你代码里的其他判断没有找到帖内输出的条件

**Comment by ego008** [comment]
如果在`公共局域`（顶栏、侧栏、底部）添加就使用下面判断
`{{if ne .PageName "article_detail"}}`
https://github.com/ego008/goyoubbs/blob/master/controller/article.go#L478

如果只想在帖内页面`私有局域`(帖子内容、回复)输出则可以直接修改模版
https://github.com/ego008/goyoubbs/blob/master/view/default/desktop/article.html
https://github.com/ego008/goyoubbs/blob/master/view/default/mobile/article.html

**Comment by Yakumo-Yukari** [comment]
> {{if ne .PageName "article_detail"}}

谢谢老大  我改成  {{if eq .PageName "article_detail"}}就可以在帖内显示了，

老大  现在使用的数据库有文档吗  我想看看怎么添加字段  和  怎么查询内容

**Comment by ego008** [comment]
数据库使用方法参考 https://github.com/ego008/youdb/blob/master/example/main.go
其实就是用json 存储数据。

可在 https://github.com/ego008/goyoubbs/blob/master/model/article.go#L13
这个article model 里添加Logo的属性/字段

必须设置Aobj.Tags，或者自己添加一个变量供模版调用....

PS: 快过年了，你怎么还那么用功。

**Comment by Yakumo-Yukari** [comment]
> 数据库使用方法参考 https://github.com/ego008/youdb/blob/master/example/main.go
> 其实就是用json 存储数据。
> 
> 可在 https://github.com/ego008/goyoubbs/blob/master/model/article.go#L13
> 这个article model 里添加Logo的属性/字段
> 
> 必须设置Aobj.Tags，或者自己添加一个变量供模版调用....
> 
> PS: 快过年了，你怎么还那么用功。

老大为什么不在帖子里面加一个分享插件呢 这样就可以方便分享到微博 微信 QQ 贴吧等平台了

PS：233    老大新年快乐，总是麻烦你有点不好意思呢，因为放假了想学点东西然后用youbbs做一个二次元社区。
