### ISSUE TITLE
老大关于用户中心个人网址跳转有问题

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ego008/goyoubbs#16]
![image](https://user-images.githubusercontent.com/12076232/51902233-76955000-23f4-11e9-8dda-a62060a166f6.png)
![image](https://user-images.githubusercontent.com/12076232/51902245-7c8b3100-23f4-11e9-91fb-269a69efabdf.png)

刚刚好奇点进了一个用户的页面 然后点了他的个人网站后跳转就会出现这样的错误

**Comment by ego008** [comment]
个人设置里的网页前缀应该是`http...`

**Comment by Yakumo-Yukari** [comment]
233  是吗  我是看别人的个人中心的  我还没注册账号  好像YouBbs 关闭了普通注册

发送自 Windows 10 版邮件应用

发件人: ego008
发送时间: 2019年1月30日 19:15
收件人: ego008/goyoubbs
抄送: Yakumo-Yukari; Author
主题: Re: [ego008/goyoubbs] 老大关于用户中心个人网址跳转有问题 (#16)

个人设置里的网页前缀应该是http...

**Comment by ego008** [comment]
发个登录信息到你的yeah 信箱了

**Comment by Yakumo-Yukari** [comment]
> 发个登录信息到你的yeah 信箱了

收到了  谢谢老大

老大 问个问题 我看代码里有判断性别来设置头像的代码 但是为什么网页上没设设定性别的功能呢？

**Comment by ego008** [comment]
写程序这苦活理应由汉子来。

**Comment by Yakumo-Yukari** [comment]
> 写程序这苦活理应由汉子来。

因为想做二次元社区  没办法只能自己什么都要从零开始学习  因为看youbbs不错所以只能慢慢一边学习一边摸索修改成二次元风格的
