### ISSUE TITLE
Hset   Zset  bug

### ISSUE THREAD

**Issue by habaor** [ego008/goyoubbs#17]
为什么不经过youdb.I2b转换使用 db.Hscan 获取数据不完整，而且无顺序

比如
db.Hset() 
    []byte() > "1" "2" 到"200"

db.Hscan("test",[]byte("20"),5)
这样写不行?获取的数据id 不连续，不完整

**Comment by ego008** [comment]
是按字节顺序排序(字符串比较顺序)，从数字角度看 2 小于 100， 但是，如果是字符串，2 是大于 100 的，因为字符串比较顺序是从左到左逐个字节进行比较。

所以引入 `I2b` 函数，原型出处 https://github.com/boltdb/bolt#autoincrementing-integer-for-the-bucket

要得到想要排序效果，有两种方式，第一种是使用内置函数 `I2b` ，第二种是给数字加上 0 作为前缀，补齐为固定长度的字符串,，例如把 2 变为 002，那么 002 就小于 100，符合你的预期。

**Comment by ywui** [comment]
谢谢，基础太差，大佬有什么指点的吗

**Comment by ego008** [comment]
自己多做项目，遇到问题多用google

**Comment by ywui** [comment]
我测试了一下for 循环1万次Hset 非常慢啊...
循环期间硬盘10mb/s的写入，不知道是什么情况...我记得mysql插入1万条秒插入啊

**Comment by ego008** [comment]
mysql 的写过程是：内存 -> cache缓存 -> 硬盘
youdb 直接 -> 硬盘，而且是事务写。

如果是多写，可尝试`Hmset`，节省报文解析时间，数量大会快很多。

```
	var data [][]byte
	data = append(data, []byte("k1"), []byte("12987887762987"))
	data = append(data, []byte("k2"), []byte("abc"))
	data = append(data, []byte("k3"), []byte("qwasww"))
	data = append(data, []byte("k4"), []byte("444"))
	data = append(data, []byte("k5"), []byte("555"))
	data = append(data, []byte("k6"), []byte("aaaa556"))
	data = append(data, []byte("k7"), []byte("77777"))
	data = append(data, []byte("k8"), []byte("88888"))

	db.Hmset("myhmset", data...)
```

**Comment by ywui** [comment]
那FillPercent这个参数能不能解决 分页浪费的问题，默认是0.5 对半,网上有人说设置为0.9可以减少4倍空间占用

**Comment by ywui** [comment]
封装的Hmset为什么不使用Batch 呀?

**Comment by ego008** [comment]
高 `FillPercent` 值对顺序写可以减少体积，但随机写会降低页面利用率，如果数据只添加，不删改可以设定`Bucket.FillPercent = 1.0`
参考 https://github.com/boltdb/bolt/issues/511#issuecomment-182509753

以后优化 [youdb](https://github.com/ego008/youdb) 可以考虑 [Batch](https://github.com/boltdb/bolt#batch-read-write-transactions) 或 [手动设置事务](https://github.com/boltdb/bolt#managing-transactions-manually)。`Batch` bug 挺多，使用后者可能性较大。

**Comment by ego008** [comment]
对数据库做点修正，修复事务锁问题 https://github.com/ego008/udb
