### ISSUE TITLE
不支持中文名注册

### ISSUE THREAD

**Issue by thewayofsword** [ego008/goyoubbs#3]
1）不支持中文注册，提示 name fmt err。换英文名注册，成功。
2）可以用英文名登陆，然后修改登录名为中文，提示成功
3）重新登录，输入中文名，不能登录，提示 name ftm err; 输入之前英文名，提示 json Decode err:key_not_found。

**Comment by ego008** [comment]
参考 `IsUserName` 和 `IsNickname` ， 后者允许中文 
https://github.com/ego008/goyoubbs/blob/master/util/stringcheck.go
