### ISSUE TITLE
API

### ISSUE THREAD

**Issue by sqzxcv** [ego008/goyoubbs#40]
请问是否有api接口, 我想基于你的项目开源一套移动版本的论坛模块, 不知道是否方便提供api接口

**Comment by ego008** [comment]
API 相关
- 路由 https://github.com/ego008/goyoubbs/blob/master/controller/app_router.go#L97
- 处理 https://github.com/ego008/goyoubbs/blob/master/controller/api_remote_post.go

**Comment by sqzxcv** [comment]
请问, 现在数据库存在的是md, 还是html呀,

**Comment by ego008** [comment]
> @ego008 请问, 现在数据库存在的是md, 还是html呀,

使用的数据库参见 https://youbbs.org/t/3214

**Comment by sqzxcv** [comment]
> > @ego008 请问, 现在数据库存在的是md, 还是html呀,
> 
> 使用的数据库参见 https://youbbs.org/t/3214

我写错了, 我的意思是帖子在数据库中存储的 原始数据是什么, 是markdown, 还是html, 我在考虑在客户端上怎么显示

**Comment by ego008** [comment]
> 我写错了, 我的意思是帖子在数据库中存储的 原始数据是什么, 是markdown, 还是html, 我在考虑在客户端上怎么显示

md

**Comment by sqzxcv** [comment]
好的, 谢谢啦
