### ISSUE TITLE
能支持下 Markdown 折叠内容

### ISSUE THREAD

**Issue by marklove5102** [ego008/goyoubbs#46]
<details>
<>展开查看1话</summary>
<pre><code>
//-----------------------1话
——校园护花高手——2021-02-18 23:20——第4话 特别的气质——第212话 暗影组织
——火爆天王——2021-02-16 23:54——第4话 不速之客1——第227话 颁奖礼3
——九阳神王——2021-02-15 21:41——第1话 马赛克下的真相——第239话 萧月玫与小皮鞭
——王牌神医——2021-02-15 21:41——第1话——第78话
——穿越西元3000后——2021-02-14 18:18——第4话 离博士1——第744话 恶魔领域1
——这里有妖气——2021-02-14 18:18——第16话 两段尸——完结活动—开奖啦！
——苍穹榜之万兽归源——2021-01-09 00:06——第5话：合力抗敌（下）——第97话：黑金狮皇
——英雄再临（英雄？我早就不当了）——2020-10-24 12:54——第四话——被盯上的库洛儿
——剑道凌天——2020-09-25 15:21——第1话 剑冢系统开启——第109话 不放，气死他们
——剑玲珑——2020-07-30 15:00——第6话 蜘蛛——第109话 抵达岭南
——绝世战魂——2020-07-30 10:21——第4话 挑衅上门——第265话 少爷
——狂女重生：纨绔七皇妃——2020-07-29 23:11——第2话 我回到了三年前？——第302话 两个黎戬？
——司少你老婆又跑了——2020-07-29 23:11——第3话 羊入虎口——第347话 你永远不会是我的
——重生豪门之强势归来——2020-07-29 23:11——第8话——特别篇中奖公布
——最后的召唤师——2020-07-29 21:04——第3话3 喵呜！独立日！——二季第11话8 毁灭者祭坛
——妙手仙医——2020-07-29 20:53——第1话 神奇的男妇科医生(1)——第40话 最终话：再见！医生
斗神养成实录  2020-07-29 23:40  ——遗书         ——本季完结           
烈火狂妃：兽性王爷硬2020-07-29 23:11  ——002泼妇会武术，谁也挡不住   ——变故   

</code></pre>
<pre><code>
降灵记
时空幸存者
陈官快递
诸天纪
劫天运
禁书世界
圣祖
踏碎仙河
虫生

我在异界的弑神之路
假装自己天下无敌
史上最强男主角

我的夫君后宫有点多
万古第一神
404事件簿-30秒后世界末日
修仙学院的最强平民
丧尸迷城
末世英雄传说
灵武帝尊
无敌剑域
极品透视小邪医
龙敖天
超能立方
逆转仙途
尊上

伏天圣主

4000年后重生异世界的大魔导师
秦侠
极道宗师
废材联盟
九域之天眼崛起
人渣改造方案
护花兵王在都市
嘴炮至尊

一品高手
全能装X系统
谐帝为尊
逆天战神
逆天神医
医等狂兵
绝世兵王
重生之都市狂仙
万古剑神
极品战兵在都市
地表最强黄金肾
灵剑尊
末世兵王
预见你的死亡
都市浪子
武神至尊 
女神的无敌特工
女总裁的近身狂兵
都市最强医仙
神剑符皇
我在末世捡属性
绝品高手
兵王之王
修真传人在都市
至尊神皇
超能狂神
蜀山风流帐
绝品强少
都市护花仙尊
异能之王者归来
都市绝品仙帝
大英雄的女友超级凶
混沌金乌
邪气凛然
鹏城诡事
极品小神医
我的极品特工老婆
龙魂特工
绝顶弃少
绝世小神医
无敌剑神
女特工升职记
不朽凡人
异能少年王
帝凰之神医弃妃
逆天仙命
神经武林之盖世无双
末世苍狼
都市超级医生
长生九千岁
绝世神尊
</code></pre>
</details>

<details>
  <summary>折叠文本</summary>
  此处可书写文本
  嗯，是可以书写文本的
<pre><code>1-1/
</code></pre>
</details>

<details>
  <summary>折叠代码块blockcode</summary>
  <pre><code>1-1/
</code></pre>
  <pre><blockcode> 
     System.out.println("虽然可以折叠代码块");
     System.out.println("但是代码无法高亮");
  </blockcode></pre>
</details>

<details>
  <summary>折叠代码块code</summary>
   <pre><code>1-1/
   </code></pre>
  <pre><code> 
     System.out.println("虽然可以折叠代码块");
     System.out.println("但是代码无法高亮");
  </code></pre>
</details>
https://keatonlao.gitee.io/a-study-note-for-markdown/syntax/%E8%AF%A6%E7%BB%86%E7%89%88/markdown-%E6%8A%98%E5%8F%A0%E5%86%85%E5%AE%B9/

**Comment by ego008** [comment]
https://github.com/ego008/goyoubbs/commit/c8f2b0d0a59d761a8b83342a8658afe4176108d8
