### ISSUE TITLE
帮你记下，图片分目录，删除帖子删图片，不能修改用户名。

### ISSUE THREAD

**Issue by xdeng** [ego008/goyoubbs#5]
帮你记下，图片分目录，删除帖子删图片，QQ注册同名自动加1，不能修改用户名。

**Comment by ego008** [comment]
Todo  :smile:

**Comment by hooqee** [comment]
如果再优化下编辑器，支持markdown 格式就更完美了，期待

**Comment by ego008** [comment]
@hooqee 新站编辑器完全可以支持`md`，官网有历史包袱。

**Comment by jpfree** [comment]
> @hooqee 新站编辑器完全可以支持`md`，官网有历史包袱。

是直接支持还是需要配置？我的输入MD语法不解析
