### ISSUE TITLE
Feed 输出有问题

### ISSUE THREAD

**Issue by tsai1993** [ego008/goyoubbs#6]
抱歉，微博帐号密码忘了，只好在这里提 bug。

https://www.youbbs.org/feed 和 https://bbs.lirencollege.xyz/feed 输出都有问题，前者没有任何输出，后者输出的 url 链接 是 http://127.0.0.1:8082/t/376，不知道怎么改。

**Comment by ego008** [comment]
https://github.com/ego008/goyoubbs/blob/master/config/config.yaml#L18

改为自己的域名

**Comment by tsai1993** [comment]
谢谢

**Comment by tsai1993** [comment]
@cmmei
